[package]
authors = ["Jacob Lindahl <jacob@near.foundation>"]
categories = ["wasm", "cryptography::cryptocurrencies", "no-std"]
description = """
Helpful functions and macros for developing smart contracts on NEAR Protocol.
"""
documentation = "https://docs.rs/near-contract-tools"
edition = "2021"
license = "GPL-3.0"
name = "near-contract-tools"
repository = "https://github.com/NEARFoundation/near-contract-tools"
version = "0.6.1"

[dependencies]
near-contract-tools-macros = {version = "=0.6.1", path = "./macros"}
near-sdk = "4.0.0"
serde = "1.0.144"
serde_json = "1.0.85"
snafu = "0.7.1"

[workspace]
members = [
  ".",
  "macros",
  "workspaces-tests",
]
