[package]
authors = ["Jacob Lindahl <jacob@near.foundation>"]
categories = ["wasm"]
description = """
Helpful functions and macros for developing smart contracts on NEAR Protocol.
"""
documentation = "https://docs.rs/near-contract-tools"
edition = "2021"
license = "GPL-3.0"
name = "near-contract-tools"
repository = "https://github.com/encody/near-contract-tools"
version = "0.5.0"

[dependencies]
near-contract-tools-macros = {version = "=0.5.0", path = "./macros"}
near-sdk = {version = "=4.1.0-pre.3", features = ["unstable"]}
serde = "1"
serde_json = "1"
thiserror = "1"

[workspace]
members = [
  ".",
  "macros",
  "workspaces-tests",
]
