[package]
name = "near-contract-tools"
version = "0.3.1"
edition = "2021"
authors = ["Jacob Lindahl <jacob@near.foundation>"]
license = "GPL-3.0"
categories = ["wasm"]
description = """
Helpful functions and macros for developing smart contracts on NEAR Protocol.
"""

[dependencies]
near-sdk = "4.0.0"
serde = "1.0.137"
serde_json = "1.0.81"
near-contract-tools-macros = { version = "=0.3.1", path = "./macros" }
