[package]
name = "near-contract-tools"
version = "0.4.0"
edition = "2021"
authors = ["Jacob Lindahl <jacob@near.foundation>"]
license = "GPL-3.0"
categories = ["wasm"]
description = """
Helpful functions and macros for developing smart contracts on NEAR Protocol.
"""
repository = "https://github.com/encody/near-contract-tools"
documentation = "https://docs.rs/near-contract-tools"

[dependencies]
near-sdk = "4"
serde = "1"
serde_json = "1"
near-contract-tools-macros = { version = "=0.4.0", path = "./macros" }
