[package]
edition = "2021"
name = "test-vm"
version = "0.1.0"

[dependencies]
near-contract-tools = {version = "=0.4.0", path = "../"}
near-sdk = "4.0.0"
near-units = "0.2.0"
serde = "1.0.140"
serde_json = "1.0.82"
workspaces = "0.4.0"
