[package]
name = "near-contract-tools-macros"
version = "0.3.2"
edition = "2021"
authors = ["Jacob Lindahl <jacob@near.foundation>"]
license = "GPL-3.0"
categories = ["wasm"]
description = """
Macros for `near-contract-tools`
"""

[dependencies]
darling = "0.14.1"
heck = "0.4.0"
quote = "1.0.18"
syn = "1.0.95"

[lib]
proc-macro = true
