[package]
name = "near-contract-tools-macros"
version = "0.3.5"
edition = "2021"
authors = ["Jacob Lindahl <jacob@near.foundation>"]
license = "GPL-3.0"
categories = ["wasm"]
description = """
Macros for `near-contract-tools`
"""

[dependencies]
darling = "0.14"
heck = "0.4"
quote = "1"
syn = "1"

[lib]
proc-macro = true
