[package]
autobins = false
edition = "2021"
name = "workspaces-tests"
version = "0.1.0"

[[bin]]
name = "counter_multisig"

[[bin]]
name = "cross_target"

[[bin]]
name = "fungible_token"

[[bin]]
name = "native_multisig"

[[bin]]
name = "simple_multisig"

[dependencies]
near-contract-tools = {path = "../"}
near-sdk = "4.0.0"
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.34"

[dev-dependencies]
tokio = "1"

[target.'cfg(not(windows))'.dev-dependencies]
workspaces = "0.4"
