[package]
autobins = false
edition = "2021"
name = "workspaces-tests"
publish = false
version = "0.1.0"

[[bin]]
name = "upgrade_bad"

[[bin]]
name = "upgrade_old_borsh"

[[bin]]
name = "upgrade_old_jsonbase64"

[[bin]]
name = "upgrade_old_raw"

[[bin]]
name = "upgrade_new"

[[bin]]
name = "counter_multisig"

[[bin]]
name = "cross_target"

[[bin]]
name = "fungible_token"

[[bin]]
name = "native_multisig"

[[bin]]
name = "simple_multisig"

[dependencies]
near-contract-tools = {path = "../"}
near-sdk = {version = "4.0.0", features = ["unstable"]}
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.34"

[dev-dependencies]
tokio = "1.21.1"

[target.'cfg(not(windows))'.dev-dependencies]
workspaces = "0.6"
