[package]
autobins = false
edition = "2021"
name = "workspaces-tests"
version = "0.1.0"

[[bin]]
name = "fungible_token"

[dependencies]
near-contract-tools = {path = "../"}
near-sdk = "4.0.0"

[dev-dependencies]
tokio = "1"

[target.'cfg(not(windows))'.dev-dependencies]
workspaces = "0.4"
