[tasks.build]
clear = true
script = """
rustup target add wasm32-unknown-unknown
cargo build --target wasm32-unknown-unknown --release --all
"""

[tasks.test]
clear = true
dependencies = ["build"]
script = """
#!/usr/bin/env bash
set -e

if [[ -n $1 ]]; then
    cargo test --package workspaces-tests --test "$1" -- --nocapture
else
    cargo test
fi
"""
