[package]
name = "workspaces-tests-utils"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(not(windows))'.dependencies]
near-sdk.workspace = true
near-workspaces = "0.8"
pretty_assertions.workspace = true
