name: Rust

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

env:
  CARGO_TERM_COLOR: always

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure Rust
        uses: dtolnay/rust-toolchain@1.64.0
        with:
          components: rustfmt
      - name: Check formatting
        run: >
          echo "::echo::on";
          cargo fmt -- --check;
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure Rust
        uses: dtolnay/rust-toolchain@1.64.0
        with:
          components: clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run linter
        run: cargo clippy -- -D warnings
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure Rust
        uses: dtolnay/rust-toolchain@1.64.0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run unit and integration tests
        run: cargo test --verbose
  workspaces-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure Rust
        uses: dtolnay/rust-toolchain@1.64.0
        with:
          targets: wasm32-unknown-unknown
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run workspaces tests
        run: >
          cd workspaces-tests;
          cargo install cargo-make;
          cargo make test;
