name: Rust

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run formatting checker
        run: >
          echo "diff=$(cargo fmt -- --check)" >> $GITHUB_ENV;
          echo "retval=$?" >> $GITHUB_ENV;
      - name: Check formatting result
        run: >
          if [[ ${retval} -ne 0 ]]; then
            echo "::echo::on";
            echo "::group::Incorrectly formatted code";
            echo "$diff";
            echo "::endgroup::";
            false;
          else
            true;
          fi
